.changeset/hot-turkeys-return.md
src/Duration.ts
src/index.ts
test/Duration.ts

Adds `Duration` data type and associated tests from https://github.com/ts-plus/stdlib/blob/main/packages/stdlib/_src/data/Duration.ts

feat: add Duration

---

.changeset/green-comics-fix.md
docs/modules/ImmutableQueue.ts.md
docs/modules/List.ts.md
docs/modules/MutableHashMap.ts.md
docs/modules/MutableListBuilder.ts.md
docs/modules/index.ts.md
src/ImmutableQueue.ts
src/index.ts
src/internal/ImmutableQueue.ts
src/internal/Iterable.ts
src/internal/List.ts
test/ImmutableQueue.ts

Adds a port of scala's immutable `Queue` implementation

feat: add ImmutableQueue

---

.changeset/nice-houses-decide.md
docs/modules/HashMap.ts.md
docs/modules/List.ts.md
docs/modules/MutableHashMap.ts.md
docs/modules/MutableHashSet.ts.md
docs/modules/MutableListBuilder.ts.md
docs/modules/MutableRef.ts.md
docs/modules/Queue.ts.md
docs/modules/index.ts.md
src/HashMap.ts
src/index.ts
src/internal/HashMap.ts
src/internal/HashMap/array.ts
src/internal/HashMap/bitwise.ts
src/internal/HashMap/config.ts
src/internal/HashMap/node.ts
src/internal/Stack.ts
test/HashMap.ts

Add the `HashMap` data type

---

.changeset/silent-clouds-admire.md
docs/modules/HashSet.ts.md
docs/modules/List.ts.md
docs/modules/MutableHashMap.ts.md
docs/modules/MutableHashSet.ts.md
docs/modules/MutableListBuilder.ts.md
docs/modules/MutableRef.ts.md
docs/modules/Queue.ts.md
docs/modules/index.ts.md
src/HashMap.ts
src/HashSet.ts
src/index.ts
src/internal/HashMap.ts
src/internal/HashMap/keySet.ts
src/internal/HashSet.ts
test/HashMap.ts
test/HashSet.ts

Add the `HashSet` data type

---

.changeset/calm-pigs-fail.md
docs/modules/Differ.ts.md
docs/modules/Differ/HashMapPatch.ts.md
docs/modules/Differ/HashSetPatch.ts.md
docs/modules/Differ/OrPatch.ts.md
docs/modules/Duration.ts.md
docs/modules/Equal.ts.md
docs/modules/Hash.ts.md
docs/modules/HashMap.ts.md
docs/modules/HashSet.ts.md
docs/modules/List.ts.md
docs/modules/MutableHashMap.ts.md
docs/modules/MutableHashSet.ts.md
docs/modules/MutableListBuilder.ts.md
docs/modules/MutableRef.ts.md
docs/modules/Queue.ts.md
docs/modules/index.ts.md
src/Differ.ts
src/Differ/HashMapPatch.ts
src/Differ/HashSetPatch.ts
src/index.ts
src/internal/Differ.ts
src/internal/Differ/ChunkPatch.ts
src/internal/Differ/HashMapPatch.ts
src/internal/Differ/HashSetPatch.ts
test/Differ.ts

Adds patches for `HashMap` and `HashSet`.

Add missing patch instances

---

.changeset/fair-students-walk.md
docs/modules/RedBlackTree.ts.md
docs/modules/index.ts.md
src/RedBlackTree.ts
src/index.ts
src/internal/Differ.ts
src/internal/RedBlackTree.ts
src/internal/RedBlackTree/iterator.ts
src/internal/RedBlackTree/node.ts
test/RedBlackTree.ts

Adds the `RedBlackTree` data type.

Add `RedBlackTree` data type

---

.changeset/rotten-ravens-joke.md
docs/modules/SafeEval.ts.md
docs/modules/index.ts.md
package.json
pnpm-lock.yaml
src/SafeEval.ts
src/index.ts
src/internal/HashMap.ts
src/internal/SafeEval.ts
test/SafeEval.ts

Adds the `SafeEval` data type.

Add `SafeEval` data type

---

.changeset/cuddly-days-tickle.md
src/Number.ts
src/String.ts
test/Boolean.ts
test/Compactable.ts
test/Endomorphism.ts
test/Function.ts
test/Number.ts
test/Option.ts
test/Predicate.ts
test/Refinement.ts
test/Result.ts
test/String.ts

- Add additional missing tests
- Fix `MonoidMultiple.combineAll`

Add additional tests and fix MonoidMultiple.combineAll

---

.changeset/cuddly-days-tickle.md
docs/modules/String.ts.md
src/Number.ts
src/String.ts
test/Boolean.ts
test/Chunk.ts
test/Compactable.ts
test/Endomorphism.ts
test/Equal.ts
test/Function.ts
test/List.ts
test/Number.ts
test/Option.ts
test/Predicate.ts
test/Refinement.ts
test/Result.ts
test/String.ts
test/index.ts

Adds missing `String` combinators.

Add missing string combinators

---

.changeset/grumpy-nails-accept.md
docs/modules/ReadonlyArray.ts.md
src/ReadonlyArray.ts
test/ReadonlyArray.ts

- Adds tests for `ReadonlyArray`
- Adds `ReadonlyArray.range`

Add tests for `ReadonlyArray`

---

test/Filterable.ts

Add tests for `Filterable`

---

test/TraversableFilterable.ts

Adds tests for `TraversableFilterable`

Add tests for `TraversableFilterable`

---

.changeset/fuzzy-moose-flash.md
src/NonEmptyReadonlyArray.ts
test/Const.ts
test/Filterable.ts
test/Identity.ts
test/MutableList.ts
test/NonEmptyReadonlyArray.ts
test/ReadonlyArray.ts

Adds additional `NonEmptyReadonlyArray` constructors:
- `from`
- `unsafeFrom`
- `make`
Also adds tests for `NonEmptyReadonlyArray`.

Add additional `NonEmptyReadonlyArray` constructors

---

src/Option.ts

closes https://github.com/fp-ts/data/pull/68

Fix-option module examples (Rebase)

---

.gitignore
src/Boolean.ts
src/Either.ts
src/Function.ts
src/NonEmptyReadonlyArray.ts
src/Number.ts
src/Option.ts
src/String.ts

closes https://github.com/fp-ts/data/pull/70

Fix result examples (Rebase)

---

.changeset/moody-stingrays-joke.md
.changeset/tall-parents-deliver.md
src/Chunk.ts
src/Equal.ts
src/Random.ts
src/index.ts
test/Chunk.ts

- Makes `Random` a public module
- Adds `Chunk.zipWithIndex` and `Chunk.zipWithIndexOffset`

Add several missing items

---

.changeset/soft-plums-raise.md
src/Chunk.ts
test/Chunk.ts

Fix Chunk.unfold

---

.changeset/long-pugs-flow.md
.gitpod.yml
src/internal/RedBlackTree.ts
test/RedBlackTree.ts

Fix RBT lessThanEqual implementation; add tests

---

.changeset/odd-emus-promise.md
docs/modules/SortedSet.ts.md
src/Chunk.ts
src/MutableHashMap.ts
src/MutableHashSet.ts
src/MutableList.ts
src/MutableQueue.ts
src/MutableRef.ts
src/SortedMap.ts
src/SortedSet.ts
src/internal/HashMap.ts
src/internal/HashSet.ts
src/internal/RedBlackTree.ts
test/Chunk.ts
test/HashMap.ts
test/HashSet.ts
test/MutableHashMap.ts
test/MutableList.ts
test/MutableQueue.ts
test/RedBlackTree.ts
test/SortedMap.ts
test/SortedSet.ts

improve stringify of custom types

---

.changeset/sharp-eels-joke.md
docs/modules/Predicate.ts.md
src/Predicate.ts
test/Predicate.ts

Added Predicate feature parity with Boolean. xor, eqv, implies,nor, nand, getSemigroupXor, getMonoidXor, getSemigroupEqv, getMonoidEqv.

feat(Predicate): added xor, eqv, implies,nor, nand

---

docs/modules/Option.ts.md
src/Option.ts
test/Option.ts

docs(Option): Adding an example and a test for the `tap` function

---

.changeset/thin-ways-rescue.md
docs/modules/Context.ts.md
src/Context.ts

Switches the names for Tag constructor to match the interface for Tag

fix(Context): correct the order of type parameters

---

.changeset/six-rice-tan.md
docs/modules/Either.ts.md
docs/modules/Option.ts.md
src/Either.ts
src/Option.ts
src/internal/Either.ts
src/internal/Option.ts
src/typeclass/TraversableFilterable.ts
test/ReadonlyArray.ts

This PR attempts at improving ability to extract generic types from structure, it should improve inference of sub-types such as effect

Carry always all generics in union members

---

.changeset/cyan-chefs-refuse.md
docs/modules/Either.ts.md
docs/modules/ReadonlyArray.ts.md
src/Either.ts
src/ReadonlyArray.ts
test/Either.ts

Similar to
- https://effect-ts.github.io/io/modules/Effect.ts.html#validateall
- https://effect-ts.github.io/io/modules/Effect.ts.html#validatealldiscard
- https://effect-ts.github.io/io/modules/Effect.ts.html#validatefirst

Either: add validateAll, validateAllDiscard, validateFirst

---

.changeset/gentle-starfishes-hunt.md
dtslint/ts4.9/Struct.ts
src/Struct.ts
test/Struct.ts

Migrated struct/evolve from fp-ts with minor changes.

feat(Struct): added evolve

---

.changeset/early-flies-mate.md
dtslint/ReadonlyRecord.ts
src/ReadonlyRecord.ts

- collect
- filterMap
- filter
- partitionMap
- partition
- traverse
Ref: https://discord.com/channels/795981131316985866/1080904799857418430/threads/1120723736967000104

ReadonlyRecord: add support for Record<K, A> to:

---

.changeset/tall-pears-build.md
docs/modules/Unify.ts.md
dtslint/Unify.ts
src/Unify.ts

Bugfix Unify on Record<string, any>

---

.changeset/small-insects-dream.md
docs/modules/Function.ts.md
src/Function.ts
test/Function.ts

Port `flow` over from fp-ts

---

.changeset/many-geese-complain.md
docs/modules/Brand.ts.md
docs/modules/Data.ts.md
docs/modules/Types.ts.md
docs/modules/Unify.ts.md
dtslint/Types.ts
src/Brand.ts
src/Data.ts
src/Types.ts

Adds a collection of types used across effect repos

feat: added Types module

---

.changeset/cool-plums-design.md
docs/modules/Encoding.ts.md
src/Encoding.ts
src/internal/Encoding/Common.ts
test/Encoding.ts

Is this what you had in mind @tim-smart ?

add `string` encoding & decoding variants
